version: "2.4"

services:
  hibiki-consumer:
    container_name: hibiki-consumer
    image: rl404/hibiki:latest
    command: ./hibiki consumer
    restart: always
    env_file: ./../.env
    network_mode: host
