name: import terraform

on: workflow_dispatch

jobs:
  import_terraform:
    name: Import Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/terraform
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Auth gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          gcp_project_id               = "${{ secrets.GCP_PROJECT_ID }}"
          gcp_region                   = "${{ secrets.GCP_REGION }}"
          gke_cluster_name             = "${{ secrets.GKE_CLUSTER_NAME }}"
          gke_location                 = "${{ secrets.GKE_LOCATION }}"
          gke_pool_name                = "${{ secrets.GKE_POOL_NAME }}"
          gke_node_preemptible         = "${{ secrets.GKE_NODE_PREEMPTIBLE }}"
          gke_node_machine_type        = "${{ secrets.GKE_NODE_MACHINE_TYPE }}"
          gcr_image_name               = "${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/hibiki:${{ needs.publish_image.outputs.img_tag }}"
          gke_deployment_consumer_name = "${{ secrets.GKE_DEPLOYMENT_CONSUMER_NAME }}"
          gke_cron_fill_name           = "${{ secrets.GKE_CRON_FILL_NAME }}"
          gke_cron_fill_schedule       = "${{ secrets.GKE_CRON_FILL_SCHEDULE }}"
          gke_cron_update_name         = "${{ secrets.GKE_CRON_UPDATE_NAME }}"
          gke_cron_update_schedule     = "${{ secrets.GKE_CRON_UPDATE_SCHEDULE }}"
          cloud_run_name               = "${{ secrets.CLOUD_RUN_NAME }}"
          cloud_run_location           = "${{ secrets.CLOUD_RUN_LOCATION }}"
          hibiki_cache_dialect         = "${{ secrets.HIBIKI_CACHE_DIALECT }}"
          hibiki_cache_address         = "${{ secrets.HIBIKI_CACHE_ADDRESS }}"
          hibiki_cache_password        = "${{ secrets.HIBIKI_CACHE_PASSWORD }}"
          hibiki_cache_time            = "${{ secrets.HIBIKI_CACHE_TIME }}"
          hibiki_db_dialect            = "${{ secrets.HIBIKI_DB_DIALECT }}"
          hibiki_db_address            = "${{ secrets.HIBIKI_DB_ADDRESS }}"
          hibiki_db_name               = "${{ secrets.HIBIKI_DB_NAME }}"
          hibiki_db_user               = "${{ secrets.HIBIKI_DB_USER }}"
          hibiki_db_password           = "${{ secrets.HIBIKI_DB_PASSWORD }}"
          hibiki_pubsub_dialect        = "${{ secrets.HIBIKI_PUBSUB_DIALECT }}"
          hibiki_pubsub_address        = "${{ secrets.HIBIKI_PUBSUB_ADDRESS }}"
          hibiki_pubsub_password       = "${{ secrets.HIBIKI_PUBSUB_PASSWORD }}"
          hibiki_mal_client_id         = "${{ secrets.HIBIKI_MAL_CLIENT_ID }}"
          hibiki_cron_update_limit     = "${{ secrets.HIBIKI_CRON_UPDATE_LIMIT }}"
          hibiki_cron_fill_limit       = "${{ secrets.HIBIKI_CRON_FILL_LIMIT }}"
          hibiki_cron_releasing_age    = "${{ secrets.HIBIKI_CRON_RELEASING_AGE }}"
          hibiki_cron_finished_age     = "${{ secrets.HIBIKI_CRON_FINISHED_AGE }}"
          hibiki_cron_not_yet_age      = "${{ secrets.HIBIKI_CRON_NOT_YET_AGE }}"
          hibiki_cron_user_manga_age   = "${{ secrets.HIBIKI_CRON_USER_MANGA_AGE }}"
          hibiki_log_json              = "${{ secrets.HIBIKI_LOG_JSON }}"
          hibiki_log_level             = "${{ secrets.HIBIKI_LOG_LEVEL }}"
          hibiki_newrelic_license_key  = "${{ secrets.HIBIKI_NEWRELIC_LICENSE_KEY }}"
          EOF
      - name: Init Terraform
        run: terraform init -backend-config "bucket=${{ secrets.GCS_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Import Terraform
        run: |
          terraform import -input=false google_container_cluster.cluster ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}
          terraform import -input=false google_container_node_pool.pool ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}/${{ secrets.GKE_POOL_NAME }}
          terraform import -input=false google_cloud_run_v2_service.server ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.CLOUD_RUN_LOCATION }}/${{ secrets.CLOUD_RUN_NAME }}
          terraform import -input=false kubernetes_deployment.consumer default/${{ secrets.GKE_DEPLOYMENT_CONSUMER_NAME }}
          terraform import -input=false kubernetes_cron_job_v1.cron_fill default/${{ secrets.GKE_CRON_FILL_NAME }}
          terraform import -input=false kubernetes_cron_job_v1.cron_update default/${{ secrets.GKE_CRON_UPDATE_NAME }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}